# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawLongpollClient, RawLongpollClient


class LongpollClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLongpollClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLongpollClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLongpollClient
        """
        return self._raw_client

    def long_poll_channel(self, channel: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        channel : str
            Channel name. Same rules as publish.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.longpoll.long_poll_channel(
            channel="channel",
        )
        """
        _response = self._raw_client.long_poll_channel(channel, request_options=request_options)
        return _response.data


class AsyncLongpollClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLongpollClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLongpollClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLongpollClient
        """
        return self._raw_client

    async def long_poll_channel(self, channel: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        channel : str
            Channel name. Same rules as publish.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.longpoll.long_poll_channel(
                channel="channel",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.long_poll_channel(channel, request_options=request_options)
        return _response.data
