// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ApiKeyScope: core.serialization.Schema<serializers.ApiKeyScope.Raw, brume.ApiKeyScope> =
    core.serialization.enum_(["publish", "read_stats", "manage_keys", "manage_project"]);

export declare namespace ApiKeyScope {
    export type Raw = "publish" | "read_stats" | "manage_keys" | "manage_project";
}
