// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConnectionInfo: core.serialization.ObjectSchema<serializers.ConnectionInfo.Raw, brume.ConnectionInfo> =
    core.serialization.object({
        state: core.serialization.unknown(),
        updatedAt: core.serialization.property("updated_at", core.serialization.string()),
        userId: core.serialization.property("user_id", core.serialization.string()),
    });

export declare namespace ConnectionInfo {
    export interface Raw {
        state?: unknown;
        updated_at: string;
        user_id: string;
    }
}
