// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PlanLimitErrorBody: core.serialization.ObjectSchema<
    serializers.PlanLimitErrorBody.Raw,
    brume.PlanLimitErrorBody
> = core.serialization.object({
    code: core.serialization.string(),
    current: core.serialization.number(),
    limit: core.serialization.number().optionalNullable(),
    message: core.serialization.string(),
    reason: core.serialization.string(),
    upgradeTier: core.serialization.string().optionalNullable(),
});

export declare namespace PlanLimitErrorBody {
    export interface Raw {
        code: string;
        current: number;
        limit?: (number | null | undefined) | null;
        message: string;
        reason: string;
        upgradeTier?: (string | null | undefined) | null;
    }
}
