// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConnectionInfo } from "./ConnectionInfo.js";

export const PresenceResponse: core.serialization.ObjectSchema<
    serializers.PresenceResponse.Raw,
    brume.PresenceResponse
> = core.serialization.object({
    channel: core.serialization.string(),
    connectionCount: core.serialization.property("connection_count", core.serialization.number()),
    presence: core.serialization.list(ConnectionInfo),
});

export declare namespace PresenceResponse {
    export interface Raw {
        channel: string;
        connection_count: number;
        presence: ConnectionInfo.Raw[];
    }
}
