// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PublishResponse: core.serialization.ObjectSchema<serializers.PublishResponse.Raw, brume.PublishResponse> =
    core.serialization.object({
        channel: core.serialization.string(),
        event: core.serialization.string(),
        recipients: core.serialization.number(),
        status: core.serialization.string(),
    });

export declare namespace PublishResponse {
    export interface Raw {
        channel: string;
        event: string;
        recipients: number;
        status: string;
    }
}
