// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Tier: core.serialization.Schema<serializers.Tier.Raw, brume.Tier> = core.serialization.enum_([
    "free",
    "starter",
    "pro",
    "business",
]);

export declare namespace Tier {
    export type Raw = "free" | "starter" | "pro" | "business";
}
