// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookDeleteResponse: core.serialization.ObjectSchema<
    serializers.WebhookDeleteResponse.Raw,
    brume.WebhookDeleteResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace WebhookDeleteResponse {
    export interface Raw {
        status: string;
    }
}
