// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookDeliveryItem: core.serialization.ObjectSchema<
    serializers.WebhookDeliveryItem.Raw,
    brume.WebhookDeliveryItem
> = core.serialization.object({
    attempts: core.serialization.number(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    eventType: core.serialization.property("event_type", core.serialization.string()),
    id: core.serialization.string(),
    lastAttemptAt: core.serialization.property("last_attempt_at", core.serialization.string().optionalNullable()),
    responseStatus: core.serialization.property("response_status", core.serialization.number().optionalNullable()),
    status: core.serialization.string(),
});

export declare namespace WebhookDeliveryItem {
    export interface Raw {
        attempts: number;
        created_at: string;
        event_type: string;
        id: string;
        last_attempt_at?: (string | null | undefined) | null;
        response_status?: (number | null | undefined) | null;
        status: string;
    }
}
