// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { WebhookDeliveryItem } from "./WebhookDeliveryItem.js";

export const WebhookDeliveryListResponse: core.serialization.ObjectSchema<
    serializers.WebhookDeliveryListResponse.Raw,
    brume.WebhookDeliveryListResponse
> = core.serialization.object({
    deliveries: core.serialization.list(WebhookDeliveryItem),
});

export declare namespace WebhookDeliveryListResponse {
    export interface Raw {
        deliveries: WebhookDeliveryItem.Raw[];
    }
}
