// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookTestResponse: core.serialization.ObjectSchema<
    serializers.WebhookTestResponse.Raw,
    brume.WebhookTestResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace WebhookTestResponse {
    export interface Raw {
        status: string;
    }
}
