// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface AnalyticsRequest {
    /** Time window in seconds. Default 3600 (1h). Clamped to [300, 21600] (5 min to 6 h). */
    windowSecs?: number;
}
