// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../index.js";

/**
 * `GET /v1/api-keys` success response.
 */
export interface ApiKeyListResponse {
    apiKeys: brume.ApiKeyListItem[];
}
