// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../index.js";

export interface ApiKeyListItem {
    environment: string;
    id: string;
    label: string;
    /** RFC-3339 timestamp of last use, or `null` if never used. */
    lastUsedAt?: string | null;
    prefix: string;
    /** Granted scopes (E6). Serializes as snake_case strings. */
    scopes: brume.ApiKeyScope[];
}
