// This file was auto-generated by Fern from our API Definition.

/**
 * `POST /v1/projects` success response. The `api_key` field is the only
 * time the raw key is returned; clients must store it immediately.
 */
export interface CreateProjectResponse {
    /**
     * The raw API key. `null` after the first call (the server does
     * not retain plaintext keys).
     */
    apiKey: string;
    /** Hex-encoded 16-byte project id. */
    id: string;
    maxConnections: number;
    name: string;
    tier: string;
}
