// This file was auto-generated by Fern from our API Definition.

/**
 * Standard error response body returned by all REST endpoints on 4xx/5xx.
 *
 * The legacy handlers emit `{"error": "..."}` (string-only). The newer
 * handlers emit `{"error": "CODE", "message": "human-readable"}`. Both
 * shapes parse into this struct; the `message` field is optional for
 * back-compat.
 */
export interface ErrorBody {
    /**
     * Short error code. Either a stable machine code (`AUTH_INVALID`,
     * `RATE_LIMITED`, `EMAIL_NOT_VERIFIED`, etc.) or a free-form string
     * for legacy handlers. SDK consumers should pattern-match the
     * well-known codes and treat unknown values as opaque failures.
     */
    error: string;
    /** Human-readable description. Absent on legacy string-only errors. */
    message?: string | null;
}
