// This file was auto-generated by Fern from our API Definition.

/**
 * `GET /readyz` failure body (HTTP 503).
 */
export interface NotReadyResponse {
    /** One of: `"db pool closed"`, `"db query failed"`, `"db query timeout"`. */
    reason: string;
    status: string;
}
