// This file was auto-generated by Fern from our API Definition.

/**
 * `PLAN_LIMIT` error body. Emitted by the publish / create-project /
 * create-key / SSE / long-poll paths when the project hits a per-axis
 * cap. The `code` is always `"PLAN_LIMIT"`; the `reason` is a closed
 * enum string SDK consumers can pattern-match on.
 */
export interface PlanLimitErrorBody {
    /** Always `"PLAN_LIMIT"`. */
    code: string;
    /** Current count for the axis that triggered the limit. */
    current: number;
    /**
     * The cap value, or `null` for unlimited (e.g. business tier
     * connection cap).
     */
    limit?: number | null;
    /**
     * Human-readable message. Includes the current/limit numbers
     * and the upgrade suggestion.
     */
    message: string;
    /**
     * The closed-set reason. See `PlanLimitReason` in
     * `channels/types.rs` for the full list.
     */
    reason: string;
    /**
     * The next tier up the ladder that lifts this axis, or `null`
     * when the customer is already on business.
     */
    upgradeTier?: string | null;
}
