// This file was auto-generated by Fern from our API Definition.

/**
 * `DELETE /v1/api-keys/:id` success response.
 */
export interface RevokeApiKeyResponse {
    /** Always `"revoked"`. */
    status: string;
}
