// This file was auto-generated by Fern from our API Definition.

/**
 * One of the four public billing tiers. The wire format is the lowercase
 * id from `tiers::TIERS`. New tiers require both a `tiers::TIERS` entry
 * AND an update to this enum's `as_str` list below.
 */
export const Tier = {
    Free: "free",
    Starter: "starter",
    Pro: "pro",
    Business: "business",
} as const;
export type Tier = (typeof Tier)[keyof typeof Tier];
