// This file was auto-generated by Fern from our API Definition.

/**
 * `POST /v1/webhooks/:id/test` success response.
 */
export interface WebhookTestResponse {
    /** Always `"queued"`. The actual delivery runs asynchronously. */
    status: string;
}
