# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key_list_response import ApiKeyListResponse
from ..types.api_key_scope import ApiKeyScope
from ..types.create_api_key_response import CreateApiKeyResponse
from ..types.revoke_api_key_response import RevokeApiKeyResponse
from .raw_client import AsyncRawApiKeysClient, RawApiKeysClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ApiKeysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiKeysClient
        """
        return self._raw_client

    def list_api_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyListResponse:
        """
        Returns a list of API keys for the authenticated project.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyListResponse
            API keys for the project (prefix only, never the raw key)

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.list_api_keys()
        """
        _response = self._raw_client.list_api_keys(request_options=request_options)
        return _response.data

    def create_api_key(
        self,
        *,
        environment: str,
        label: str,
        scopes: typing.Optional[typing.Sequence[ApiKeyScope]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateApiKeyResponse:
        """
        Creates a new API key for the authenticated project.

        Parameters
        ----------
        environment : str
            `"live"` or `"test"`. Determines the key prefix
            (`pk_live_` vs `pk_test_`) and the default scope set.

        label : str
            Human-readable label. Shown in the dashboard.

        scopes : typing.Optional[typing.Sequence[ApiKeyScope]]
            Optional explicit scopes. Omit to receive the default scope set
            (`publish`, `read_stats`, `manage_keys`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateApiKeyResponse
            API key created. The `key` field is the raw key, returned exactly once.

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.create_api_key(
            environment="environment",
            label="label",
        )
        """
        _response = self._raw_client.create_api_key(
            environment=environment, label=label, scopes=scopes, request_options=request_options
        )
        return _response.data

    def revoke_api_key(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevokeApiKeyResponse:
        """
        Revokes an API key for the authenticated project.

        Parameters
        ----------
        id : str
            Hex-encoded API key id (16 bytes → 32 hex chars).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevokeApiKeyResponse
            Key revoked

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.revoke_api_key(
            id="id",
        )
        """
        _response = self._raw_client.revoke_api_key(id, request_options=request_options)
        return _response.data


class AsyncApiKeysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiKeysClient
        """
        return self._raw_client

    async def list_api_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyListResponse:
        """
        Returns a list of API keys for the authenticated project.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyListResponse
            API keys for the project (prefix only, never the raw key)

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.list_api_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_api_keys(request_options=request_options)
        return _response.data

    async def create_api_key(
        self,
        *,
        environment: str,
        label: str,
        scopes: typing.Optional[typing.Sequence[ApiKeyScope]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateApiKeyResponse:
        """
        Creates a new API key for the authenticated project.

        Parameters
        ----------
        environment : str
            `"live"` or `"test"`. Determines the key prefix
            (`pk_live_` vs `pk_test_`) and the default scope set.

        label : str
            Human-readable label. Shown in the dashboard.

        scopes : typing.Optional[typing.Sequence[ApiKeyScope]]
            Optional explicit scopes. Omit to receive the default scope set
            (`publish`, `read_stats`, `manage_keys`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateApiKeyResponse
            API key created. The `key` field is the raw key, returned exactly once.

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.create_api_key(
                environment="environment",
                label="label",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_api_key(
            environment=environment, label=label, scopes=scopes, request_options=request_options
        )
        return _response.data

    async def revoke_api_key(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevokeApiKeyResponse:
        """
        Revokes an API key for the authenticated project.

        Parameters
        ----------
        id : str
            Hex-encoded API key id (16 bytes → 32 hex chars).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevokeApiKeyResponse
            Key revoked

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.revoke_api_key(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_api_key(id, request_options=request_options)
        return _response.data
