// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateWebhookRequest: core.serialization.Schema<
    serializers.CreateWebhookRequest.Raw,
    brume.CreateWebhookRequest
> = core.serialization.object({
    events: core.serialization.list(core.serialization.string()),
    url: core.serialization.string(),
});

export declare namespace CreateWebhookRequest {
    export interface Raw {
        events: string[];
        url: string;
    }
}
