// This file was auto-generated by Fern from our API Definition.

import type * as brume from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateProjectTierRequest: core.serialization.Schema<
    serializers.UpdateProjectTierRequest.Raw,
    brume.UpdateProjectTierRequest
> = core.serialization.object({
    tier: core.serialization.string(),
});

export declare namespace UpdateProjectTierRequest {
    export interface Raw {
        tier: string;
    }
}
