// Code generated by Fern. DO NOT EDIT.

package sse

import (
    context "context"
    http "net/http"

    brume "github.com/brumehq/brume-rest-go"
    core "github.com/brumehq/brume-rest-go/core"
    internal "github.com/brumehq/brume-rest-go/internal"
    option "github.com/brumehq/brume-rest-go/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) SubscribeSse(
    ctx context.Context,
    // Channel name. Same rules as publish.
    channel string,
    opts ...option.RequestOption,
) (*core.Response[any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/sse/%v",
        channel,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            ErrorDecoder: internal.NewErrorDecoder(brume.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: nil,
    }, nil
}

