// Code generated by Fern. DO NOT EDIT.

package longpoll

import (
    context "context"
    os "os"

    core "github.com/brumehq/brume-rest-go/core"
    internal "github.com/brumehq/brume-rest-go/internal"
    option "github.com/brumehq/brume-rest-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.APIKey == "" {
        options.APIKey = os.Getenv("BRUME_API_KEY")
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (c *Client) LongPollChannel(
    ctx context.Context,
    // Channel name. Same rules as publish.
    channel string,
    opts ...option.RequestOption,
) error{
    _, err := c.WithRawResponse.LongPollChannel(
        ctx,
        channel,
        opts...,
    )
    if err != nil {
        return err
    }
    return nil
}

