/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.ApiKeyListResponse;
import dev.brume.types.CreateApiKeyRequest;
import dev.brume.types.CreateApiKeyResponse;
import dev.brume.types.RevokeApiKeyResponse;
import java.lang.String;

public class ApiKeysClient {
  protected final ClientOptions clientOptions;

  private final RawApiKeysClient rawClient;

  public ApiKeysClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawApiKeysClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawApiKeysClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns a list of API keys for the authenticated project.
   */
  public ApiKeyListResponse listApiKeys() {
    return this.rawClient.listApiKeys().body();
  }

  /**
   * Returns a list of API keys for the authenticated project.
   */
  public ApiKeyListResponse listApiKeys(RequestOptions requestOptions) {
    return this.rawClient.listApiKeys(requestOptions).body();
  }

  /**
   * Creates a new API key for the authenticated project.
   */
  public CreateApiKeyResponse createApiKey(CreateApiKeyRequest request) {
    return this.rawClient.createApiKey(request).body();
  }

  /**
   * Creates a new API key for the authenticated project.
   */
  public CreateApiKeyResponse createApiKey(CreateApiKeyRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createApiKey(request, requestOptions).body();
  }

  /**
   * Revokes an API key for the authenticated project.
   */
  public RevokeApiKeyResponse revokeApiKey(String id) {
    return this.rawClient.revokeApiKey(id).body();
  }

  /**
   * Revokes an API key for the authenticated project.
   */
  public RevokeApiKeyResponse revokeApiKey(String id, RequestOptions requestOptions) {
    return this.rawClient.revokeApiKey(id, requestOptions).body();
  }
}
