/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.ChannelListResponse;
import dev.brume.types.ConnectRequest;
import dev.brume.types.PresenceResponse;
import dev.brume.types.PublishRequest;
import dev.brume.types.PublishResponse;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;

public class AsyncChannelsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawChannelsClient rawClient;

  public AsyncChannelsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawChannelsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawChannelsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns a list of all channels for the authenticated project.
   */
  public CompletableFuture<ChannelListResponse> listChannels() {
    return this.rawClient.listChannels().thenApply(response -> response.body());
  }

  /**
   * Returns a list of all channels for the authenticated project.
   */
  public CompletableFuture<ChannelListResponse> listChannels(RequestOptions requestOptions) {
    return this.rawClient.listChannels(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the current presence roster for a channel.
   */
  public CompletableFuture<PresenceResponse> getPresence(String channel) {
    return this.rawClient.getPresence(channel).thenApply(response -> response.body());
  }

  /**
   * Returns the current presence roster for a channel.
   */
  public CompletableFuture<PresenceResponse> getPresence(String channel,
      RequestOptions requestOptions) {
    return this.rawClient.getPresence(channel, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Server-side REST publish endpoint for non-WebSocket backends
   * (cron jobs, webhooks, queue workers).
   */
  public CompletableFuture<PublishResponse> publish(String channel, PublishRequest request) {
    return this.rawClient.publish(channel, request).thenApply(response -> response.body());
  }

  /**
   * Server-side REST publish endpoint for non-WebSocket backends
   * (cron jobs, webhooks, queue workers).
   */
  public CompletableFuture<PublishResponse> publish(String channel, PublishRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.publish(channel, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * JWT extraction priority:
   * <ol>
   * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
   * token out of access logs, browser history, and referer headers).</li>
   * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
   * </ol>
   * <p>If auth fails, returns an HTTP error response without upgrading.</p>
   */
  public CompletableFuture<Void> connect() {
    return this.rawClient.connect().thenApply(response -> response.body());
  }

  /**
   * JWT extraction priority:
   * <ol>
   * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
   * token out of access logs, browser history, and referer headers).</li>
   * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
   * </ol>
   * <p>If auth fails, returns an HTTP error response without upgrading.</p>
   */
  public CompletableFuture<Void> connect(RequestOptions requestOptions) {
    return this.rawClient.connect(requestOptions).thenApply(response -> response.body());
  }

  /**
   * JWT extraction priority:
   * <ol>
   * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
   * token out of access logs, browser history, and referer headers).</li>
   * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
   * </ol>
   * <p>If auth fails, returns an HTTP error response without upgrading.</p>
   */
  public CompletableFuture<Void> connect(ConnectRequest request) {
    return this.rawClient.connect(request).thenApply(response -> response.body());
  }

  /**
   * JWT extraction priority:
   * <ol>
   * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
   * token out of access logs, browser history, and referer headers).</li>
   * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
   * </ol>
   * <p>If auth fails, returns an HTTP error response without upgrading.</p>
   */
  public CompletableFuture<Void> connect(ConnectRequest request, RequestOptions requestOptions) {
    return this.rawClient.connect(request, requestOptions).thenApply(response -> response.body());
  }
}
