/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.CreateWebhookRequest;
import dev.brume.types.WebhookCreatedResponse;
import dev.brume.types.WebhookDeleteResponse;
import dev.brume.types.WebhookDeliveryListResponse;
import dev.brume.types.WebhookListResponse;
import dev.brume.types.WebhookTestResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncWebhooksClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawWebhooksClient rawClient;

  public AsyncWebhooksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawWebhooksClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawWebhooksClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<WebhookListResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookListResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookCreatedResponse> create(CreateWebhookRequest request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookCreatedResponse> create(CreateWebhookRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookDeleteResponse> delete(String id) {
    return this.rawClient.delete(id).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookDeleteResponse> delete(String id, RequestOptions requestOptions) {
    return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookDeliveryListResponse> listDeliveries(String id) {
    return this.rawClient.listDeliveries(id).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookDeliveryListResponse> listDeliveries(String id,
      RequestOptions requestOptions) {
    return this.rawClient.listDeliveries(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookTestResponse> test(String id) {
    return this.rawClient.test(id).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookTestResponse> test(String id, RequestOptions requestOptions) {
    return this.rawClient.test(id, requestOptions).thenApply(response -> response.body());
  }
}
