/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import com.fasterxml.jackson.core.JsonProcessingException;
import dev.brume.core.BrumeClientApiException;
import dev.brume.core.BrumeClientException;
import dev.brume.core.BrumeClientHttpResponse;
import dev.brume.core.ClientOptions;
import dev.brume.core.ObjectMappers;
import dev.brume.core.RequestOptions;
import dev.brume.errors.ServiceUnavailableError;
import dev.brume.types.ReadyzResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawPublicClient {
  protected final ClientOptions clientOptions;

  public AsyncRawPublicClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<BrumeClientHttpResponse<Void>> health() {
    return health(null);
  }

  public CompletableFuture<BrumeClientHttpResponse<Void>> health(RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("health");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<BrumeClientHttpResponse<Void>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new BrumeClientHttpResponse<>(null, response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Prometheus-compatible metrics endpoint.
     */
    public CompletableFuture<BrumeClientHttpResponse<Void>> metrics() {
      return metrics(null);
    }

    /**
     * Prometheus-compatible metrics endpoint.
     */
    public CompletableFuture<BrumeClientHttpResponse<Void>> metrics(RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("metrics");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BrumeClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new BrumeClientHttpResponse<>(null, response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
       * fetch the spec without holding a Brume API key. The spec itself only
       * describes existence of routes; it does not leak auth bypass — every
       * documented operation still requires the appropriate security
       * credentials at request time.
       */
      public CompletableFuture<BrumeClientHttpResponse<Void>> openapiSpec() {
        return openapiSpec(null);
      }

      /**
       * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
       * fetch the spec without holding a Brume API key. The spec itself only
       * describes existence of routes; it does not leak auth bypass — every
       * documented operation still requires the appropriate security
       * credentials at request time.
       */
      public CompletableFuture<BrumeClientHttpResponse<Void>> openapiSpec(
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("openapi.json");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<BrumeClientHttpResponse<Void>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new BrumeClientHttpResponse<>(null, response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<BrumeClientHttpResponse<ReadyzResponse>> readyz() {
          return readyz(null);
        }

        public CompletableFuture<BrumeClientHttpResponse<ReadyzResponse>> readyz(
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("readyz");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<BrumeClientHttpResponse<ReadyzResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new BrumeClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ReadyzResponse.class), response));
                    return;
                  }
                  try {
                    if (response.code() == 503) {
                      future.completeExceptionally(new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
