/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import com.fasterxml.jackson.core.JsonProcessingException;
import dev.brume.core.BrumeClientApiException;
import dev.brume.core.BrumeClientException;
import dev.brume.core.BrumeClientHttpResponse;
import dev.brume.core.ClientOptions;
import dev.brume.core.MediaTypes;
import dev.brume.core.ObjectMappers;
import dev.brume.core.QueryStringMapper;
import dev.brume.core.RequestOptions;
import dev.brume.errors.BadRequestError;
import dev.brume.errors.ContentTooLargeError;
import dev.brume.errors.ForbiddenError;
import dev.brume.errors.TooManyRequestsError;
import dev.brume.errors.UnauthorizedError;
import dev.brume.types.ChannelListResponse;
import dev.brume.types.ConnectRequest;
import dev.brume.types.ErrorBody;
import dev.brume.types.PresenceResponse;
import dev.brume.types.PublishRequest;
import dev.brume.types.PublishResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawChannelsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawChannelsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns a list of all channels for the authenticated project.
   */
  public CompletableFuture<BrumeClientHttpResponse<ChannelListResponse>> listChannels() {
    return listChannels(null);
  }

  /**
   * Returns a list of all channels for the authenticated project.
   */
  public CompletableFuture<BrumeClientHttpResponse<ChannelListResponse>> listChannels(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/channels");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<BrumeClientHttpResponse<ChannelListResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new BrumeClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ChannelListResponse.class), response));
              return;
            }
            try {
              if (response.code() == 401) {
                future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Returns the current presence roster for a channel.
     */
    public CompletableFuture<BrumeClientHttpResponse<PresenceResponse>> getPresence(
        String channel) {
      return getPresence(channel,null);
    }

    /**
     * Returns the current presence roster for a channel.
     */
    public CompletableFuture<BrumeClientHttpResponse<PresenceResponse>> getPresence(String channel,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("v1/channels")
        .addPathSegment(channel)
        .addPathSegments("presence");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BrumeClientHttpResponse<PresenceResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new BrumeClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PresenceResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Server-side REST publish endpoint for non-WebSocket backends
       * (cron jobs, webhooks, queue workers).
       */
      public CompletableFuture<BrumeClientHttpResponse<PublishResponse>> publish(String channel,
          PublishRequest request) {
        return publish(channel,request,null);
      }

      /**
       * Server-side REST publish endpoint for non-WebSocket backends
       * (cron jobs, webhooks, queue workers).
       */
      public CompletableFuture<BrumeClientHttpResponse<PublishResponse>> publish(String channel,
          PublishRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("v1/channels")
          .addPathSegment(channel)
          .addPathSegments("publish");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new BrumeClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<BrumeClientHttpResponse<PublishResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new BrumeClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PublishResponse.class), response));
                  return;
                }
                try {
                  switch (response.code()) {
                    case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                    return;
                    case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                    return;
                    case 413:future.completeExceptionally(new ContentTooLargeError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                    return;
                    case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * JWT extraction priority:
         * <ol>
         * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
         * token out of access logs, browser history, and referer headers).</li>
         * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
         * </ol>
         * <p>If auth fails, returns an HTTP error response without upgrading.</p>
         */
        public CompletableFuture<BrumeClientHttpResponse<Void>> connect() {
          return connect(ConnectRequest.builder().build());
        }

        /**
         * JWT extraction priority:
         * <ol>
         * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
         * token out of access logs, browser history, and referer headers).</li>
         * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
         * </ol>
         * <p>If auth fails, returns an HTTP error response without upgrading.</p>
         */
        public CompletableFuture<BrumeClientHttpResponse<Void>> connect(
            RequestOptions requestOptions) {
          return connect(ConnectRequest.builder().build(),requestOptions);
        }

        /**
         * JWT extraction priority:
         * <ol>
         * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
         * token out of access logs, browser history, and referer headers).</li>
         * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
         * </ol>
         * <p>If auth fails, returns an HTTP error response without upgrading.</p>
         */
        public CompletableFuture<BrumeClientHttpResponse<Void>> connect(ConnectRequest request) {
          return connect(request,null);
        }

        /**
         * JWT extraction priority:
         * <ol>
         * <li><code>Sec-WebSocket-Protocol: brume.token.&lt;jwt&gt;</code> (recommended — keeps the
         * token out of access logs, browser history, and referer headers).</li>
         * <li><code>?token=&lt;jwt&gt;</code> query parameter (legacy; emits a deprecation warning).</li>
         * </ol>
         * <p>If auth fails, returns an HTTP error response without upgrading.</p>
         */
        public CompletableFuture<BrumeClientHttpResponse<Void>> connect(ConnectRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("v1/connect");if (request.getToken().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "token", request.getToken().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<BrumeClientHttpResponse<Void>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new BrumeClientHttpResponse<>(null, response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    switch (response.code()) {
                      case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                      return;
                      case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorBody.class), response));
                      return;
                      case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BrumeClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
