/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.AnalyticsRequest;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class AsyncStatsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawStatsClient rawClient;

  public AsyncStatsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawStatsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawStatsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns the project's analytics history as a list of snapshots
   * (oldest first). Snapshots are sampled every 30s in-process. The
   * response includes the last <code>window / interval</code> entries. Empty
   * state is an empty <code>snapshots</code> array — never faked data.
   * <p>Response body is documented as <code>additionalProperties: true</code> for
   * the same reason as <code>/v1/stats</code>: the shape is pinned by tests.</p>
   */
  public CompletableFuture<Map<String, Object>> analytics() {
    return this.rawClient.analytics().thenApply(response -> response.body());
  }

  /**
   * Returns the project's analytics history as a list of snapshots
   * (oldest first). Snapshots are sampled every 30s in-process. The
   * response includes the last <code>window / interval</code> entries. Empty
   * state is an empty <code>snapshots</code> array — never faked data.
   * <p>Response body is documented as <code>additionalProperties: true</code> for
   * the same reason as <code>/v1/stats</code>: the shape is pinned by tests.</p>
   */
  public CompletableFuture<Map<String, Object>> analytics(RequestOptions requestOptions) {
    return this.rawClient.analytics(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the project's analytics history as a list of snapshots
   * (oldest first). Snapshots are sampled every 30s in-process. The
   * response includes the last <code>window / interval</code> entries. Empty
   * state is an empty <code>snapshots</code> array — never faked data.
   * <p>Response body is documented as <code>additionalProperties: true</code> for
   * the same reason as <code>/v1/stats</code>: the shape is pinned by tests.</p>
   */
  public CompletableFuture<Map<String, Object>> analytics(AnalyticsRequest request) {
    return this.rawClient.analytics(request).thenApply(response -> response.body());
  }

  /**
   * Returns the project's analytics history as a list of snapshots
   * (oldest first). Snapshots are sampled every 30s in-process. The
   * response includes the last <code>window / interval</code> entries. Empty
   * state is an empty <code>snapshots</code> array — never faked data.
   * <p>Response body is documented as <code>additionalProperties: true</code> for
   * the same reason as <code>/v1/stats</code>: the shape is pinned by tests.</p>
   */
  public CompletableFuture<Map<String, Object>> analytics(AnalyticsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.analytics(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns project-level and global connection/channel statistics.
   * <p>Backwards compatibility: existing fields are preserved exactly. New
   * fields added in 2026-06-11 (latency, postgres_lag, dropped_messages,
   * slow_consumer_disconnections, dead_connections_cleaned,
   * auth_failures_last_minute, plan_limit_rejections, top_channels) are
   * additive — older dashboard clients keep working.</p>
   * <p>Response body is documented as <code>additionalProperties: true</code> because
   * the exact JSON shape is pinned by ~10 unit tests in this file. A
   * future PR can type the envelope; for now SDK consumers will see
   * <code>Record&lt;string, any&gt;</code>.</p>
   */
  public CompletableFuture<Map<String, Object>> getStats() {
    return this.rawClient.getStats().thenApply(response -> response.body());
  }

  /**
   * Returns project-level and global connection/channel statistics.
   * <p>Backwards compatibility: existing fields are preserved exactly. New
   * fields added in 2026-06-11 (latency, postgres_lag, dropped_messages,
   * slow_consumer_disconnections, dead_connections_cleaned,
   * auth_failures_last_minute, plan_limit_rejections, top_channels) are
   * additive — older dashboard clients keep working.</p>
   * <p>Response body is documented as <code>additionalProperties: true</code> because
   * the exact JSON shape is pinned by ~10 unit tests in this file. A
   * future PR can type the envelope; for now SDK consumers will see
   * <code>Record&lt;string, any&gt;</code>.</p>
   */
  public CompletableFuture<Map<String, Object>> getStats(RequestOptions requestOptions) {
    return this.rawClient.getStats(requestOptions).thenApply(response -> response.body());
  }
}
