/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.CreateProjectRequest;
import dev.brume.types.CreateProjectResponse;
import dev.brume.types.ProjectResponse;
import dev.brume.types.UpdateProjectTierRequest;
import dev.brume.types.UpdateProjectTierResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncProjectsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawProjectsClient rawClient;

  public AsyncProjectsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawProjectsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawProjectsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns full project info for the dashboard.
   */
  public CompletableFuture<ProjectResponse> getProject() {
    return this.rawClient.getProject().thenApply(response -> response.body());
  }

  /**
   * Returns full project info for the dashboard.
   */
  public CompletableFuture<ProjectResponse> getProject(RequestOptions requestOptions) {
    return this.rawClient.getProject(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new project with an initial API key. Gated on email verification.
   */
  public CompletableFuture<CreateProjectResponse> createProject(CreateProjectRequest request) {
    return this.rawClient.createProject(request).thenApply(response -> response.body());
  }

  /**
   * Creates a new project with an initial API key. Gated on email verification.
   */
  public CompletableFuture<CreateProjectResponse> createProject(CreateProjectRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createProject(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Internal sync endpoint used by the dashboard after Polar.sh webhook
   * processing. Gated by <code>BRUME_INTERNAL_TOKEN</code>.
   */
  public CompletableFuture<UpdateProjectTierResponse> updateProjectTier(String id,
      UpdateProjectTierRequest request) {
    return this.rawClient.updateProjectTier(id, request).thenApply(response -> response.body());
  }

  /**
   * Internal sync endpoint used by the dashboard after Polar.sh webhook
   * processing. Gated by <code>BRUME_INTERNAL_TOKEN</code>.
   */
  public CompletableFuture<UpdateProjectTierResponse> updateProjectTier(String id,
      UpdateProjectTierRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateProjectTier(id, request, requestOptions).thenApply(response -> response.body());
  }
}
