/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;

public class AsyncLongpollClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawLongpollClient rawClient;

  public AsyncLongpollClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawLongpollClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawLongpollClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<Void> longPollChannel(String channel) {
    return this.rawClient.longPollChannel(channel).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> longPollChannel(String channel, RequestOptions requestOptions) {
    return this.rawClient.longPollChannel(channel, requestOptions).thenApply(response -> response.body());
  }
}
