/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.ReadyzResponse;

public class PublicClient {
  protected final ClientOptions clientOptions;

  private final RawPublicClient rawClient;

  public PublicClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawPublicClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawPublicClient withRawResponse() {
    return this.rawClient;
  }

  public void health() {
    this.rawClient.health().body();
  }

  public void health(RequestOptions requestOptions) {
    this.rawClient.health(requestOptions).body();
  }

  /**
   * Prometheus-compatible metrics endpoint.
   */
  public void metrics() {
    this.rawClient.metrics().body();
  }

  /**
   * Prometheus-compatible metrics endpoint.
   */
  public void metrics(RequestOptions requestOptions) {
    this.rawClient.metrics(requestOptions).body();
  }

  /**
   * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
   * fetch the spec without holding a Brume API key. The spec itself only
   * describes existence of routes; it does not leak auth bypass — every
   * documented operation still requires the appropriate security
   * credentials at request time.
   */
  public void openapiSpec() {
    this.rawClient.openapiSpec().body();
  }

  /**
   * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
   * fetch the spec without holding a Brume API key. The spec itself only
   * describes existence of routes; it does not leak auth bypass — every
   * documented operation still requires the appropriate security
   * credentials at request time.
   */
  public void openapiSpec(RequestOptions requestOptions) {
    this.rawClient.openapiSpec(requestOptions).body();
  }

  public ReadyzResponse readyz() {
    return this.rawClient.readyz().body();
  }

  public ReadyzResponse readyz(RequestOptions requestOptions) {
    return this.rawClient.readyz(requestOptions).body();
  }
}
