/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import com.fasterxml.jackson.core.JsonProcessingException;
import dev.brume.core.BrumeClientApiException;
import dev.brume.core.BrumeClientException;
import dev.brume.core.BrumeClientHttpResponse;
import dev.brume.core.ClientOptions;
import dev.brume.core.ObjectMappers;
import dev.brume.core.RequestOptions;
import dev.brume.errors.ServiceUnavailableError;
import dev.brume.types.ReadyzResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPublicClient {
  protected final ClientOptions clientOptions;

  public RawPublicClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public BrumeClientHttpResponse<Void> health() {
    return health(null);
  }

  public BrumeClientHttpResponse<Void> health(RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("health");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new BrumeClientHttpResponse<>(null, response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new BrumeClientException("Network error executing HTTP request", e);
      }
    }

    /**
     * Prometheus-compatible metrics endpoint.
     */
    public BrumeClientHttpResponse<Void> metrics() {
      return metrics(null);
    }

    /**
     * Prometheus-compatible metrics endpoint.
     */
    public BrumeClientHttpResponse<Void> metrics(RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("metrics");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          if (response.isSuccessful()) {
            return new BrumeClientHttpResponse<>(null, response);
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new BrumeClientException("Network error executing HTTP request", e);
        }
      }

      /**
       * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
       * fetch the spec without holding a Brume API key. The spec itself only
       * describes existence of routes; it does not leak auth bypass — every
       * documented operation still requires the appropriate security
       * credentials at request time.
       */
      public BrumeClientHttpResponse<Void> openapiSpec() {
        return openapiSpec(null);
      }

      /**
       * Public (no auth) so SDK-generation tools (Fern, Stainless, etc.) can
       * fetch the spec without holding a Brume API key. The spec itself only
       * describes existence of routes; it does not leak auth bypass — every
       * documented operation still requires the appropriate security
       * credentials at request time.
       */
      public BrumeClientHttpResponse<Void> openapiSpec(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("openapi.json");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return new BrumeClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new BrumeClientException("Network error executing HTTP request", e);
          }
        }

        public BrumeClientHttpResponse<ReadyzResponse> readyz() {
          return readyz(null);
        }

        public BrumeClientHttpResponse<ReadyzResponse> readyz(RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("readyz");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new BrumeClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ReadyzResponse.class), response);
              }
              try {
                if (response.code() == 503) {
                  throw new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new BrumeClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new BrumeClientException("Network error executing HTTP request", e);
            }
          }
        }
