/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume;

import dev.brume.core.ClientOptions;
import dev.brume.core.RequestOptions;
import dev.brume.types.CreateWebhookRequest;
import dev.brume.types.WebhookCreatedResponse;
import dev.brume.types.WebhookDeleteResponse;
import dev.brume.types.WebhookDeliveryListResponse;
import dev.brume.types.WebhookListResponse;
import dev.brume.types.WebhookTestResponse;
import java.lang.String;

public class WebhooksClient {
  protected final ClientOptions clientOptions;

  private final RawWebhooksClient rawClient;

  public WebhooksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawWebhooksClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawWebhooksClient withRawResponse() {
    return this.rawClient;
  }

  public WebhookListResponse list() {
    return this.rawClient.list().body();
  }

  public WebhookListResponse list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).body();
  }

  public WebhookCreatedResponse create(CreateWebhookRequest request) {
    return this.rawClient.create(request).body();
  }

  public WebhookCreatedResponse create(CreateWebhookRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  public WebhookDeleteResponse delete(String id) {
    return this.rawClient.delete(id).body();
  }

  public WebhookDeleteResponse delete(String id, RequestOptions requestOptions) {
    return this.rawClient.delete(id, requestOptions).body();
  }

  public WebhookDeliveryListResponse listDeliveries(String id) {
    return this.rawClient.listDeliveries(id).body();
  }

  public WebhookDeliveryListResponse listDeliveries(String id, RequestOptions requestOptions) {
    return this.rawClient.listDeliveries(id, requestOptions).body();
  }

  public WebhookTestResponse test(String id) {
    return this.rawClient.test(id).body();
  }

  public WebhookTestResponse test(String id, RequestOptions requestOptions) {
    return this.rawClient.test(id, requestOptions).body();
  }
}
