# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_key_scope import ApiKeyScope


class CreateApiKeyResponse(UniversalBaseModel):
    """
    `POST /v1/api-keys` success response. The `key` field is the raw
    key returned exactly once; clients must store it before navigating
    away.
    """

    environment: str
    id: str = pydantic.Field()
    """
    Hex-encoded key id.
    """

    key: str = pydantic.Field()
    """
    The raw API key. Only returned by the create endpoint.
    """

    label: str
    prefix: str = pydantic.Field()
    """
    28-char prefix used for O(1) lookup. Safe to display.
    """

    scopes: typing.List[ApiKeyScope] = pydantic.Field()
    """
    Granted scopes (E6). Serializes as the snake_case string form
    (`"publish"`, `"read_stats"`, `"manage_keys"`, `"manage_project"`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
