# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateProjectResponse(UniversalBaseModel):
    """
    `POST /v1/projects` success response. The `api_key` field is the only
    time the raw key is returned; clients must store it immediately.
    """

    api_key: str = pydantic.Field()
    """
    The raw API key. `null` after the first call (the server does
    not retain plaintext keys).
    """

    id: str = pydantic.Field()
    """
    Hex-encoded 16-byte project id.
    """

    max_connections: int
    name: str
    tier: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
