# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ErrorBody(UniversalBaseModel):
    """
    Standard error response body returned by all REST endpoints on 4xx/5xx.

    The legacy handlers emit `{"error": "..."}` (string-only). The newer
    handlers emit `{"error": "CODE", "message": "human-readable"}`. Both
    shapes parse into this struct; the `message` field is optional for
    back-compat.
    """

    error: str = pydantic.Field()
    """
    Short error code. Either a stable machine code (`AUTH_INVALID`,
    `RATE_LIMITED`, `EMAIL_NOT_VERIFIED`, etc.) or a free-form string
    for legacy handlers. SDK consumers should pattern-match the
    well-known codes and treat unknown values as opaque failures.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable description. Absent on legacy string-only errors.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
