# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PlanLimitErrorBody(UniversalBaseModel):
    """
    `PLAN_LIMIT` error body. Emitted by the publish / create-project /
    create-key / SSE / long-poll paths when the project hits a per-axis
    cap. The `code` is always `"PLAN_LIMIT"`; the `reason` is a closed
    enum string SDK consumers can pattern-match on.
    """

    code: str = pydantic.Field()
    """
    Always `"PLAN_LIMIT"`.
    """

    current: int = pydantic.Field()
    """
    Current count for the axis that triggered the limit.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    The cap value, or `null` for unlimited (e.g. business tier
    connection cap).
    """

    message: str = pydantic.Field()
    """
    Human-readable message. Includes the current/limit numbers
    and the upgrade suggestion.
    """

    reason: str = pydantic.Field()
    """
    The closed-set reason. See `PlanLimitReason` in
    `channels/types.rs` for the full list.
    """

    upgrade_tier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="upgradeTier"),
        pydantic.Field(
            alias="upgradeTier",
            description="The next tier up the ladder that lifts this axis, or `null`\nwhen the customer is already on business.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
