# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PublishResponse(UniversalBaseModel):
    """
    `POST /v1/channels/:channel/publish` success response.
    """

    channel: str
    event: str
    recipients: int = pydantic.Field()
    """
    Number of subscribers the message was fanned out to.
    """

    status: str = pydantic.Field()
    """
    Always `"published"`. Reserved for future state changes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
