# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookDeliveryItem(UniversalBaseModel):
    attempts: int
    created_at: str = pydantic.Field()
    """
    RFC-3339 timestamp of delivery creation.
    """

    event_type: str
    id: str
    last_attempt_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    RFC-3339 timestamp of the most recent attempt, or `null`.
    """

    response_status: typing.Optional[int] = pydantic.Field(default=None)
    """
    HTTP status code of the most recent attempt, or `null`.
    """

    status: str = pydantic.Field()
    """
    `"pending" | "delivered" | "failed"`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
