# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookCreatedResponse(UniversalBaseModel):
    """
    `POST /v1/webhooks` success response. Includes the `secret` field
    which is only returned at creation time.
    """

    events: typing.List[str]
    id: str
    secret: str = pydantic.Field()
    """
    HMAC-SHA256 secret used to sign deliveries. Only returned once.
    """

    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
