# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookTestResponse(UniversalBaseModel):
    """
    `POST /v1/webhooks/:id/test` success response.
    """

    status: str = pydantic.Field()
    """
    Always `"queued"`. The actual delivery runs asynchronously.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.ignore
