# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_project_response import CreateProjectResponse
from ..types.project_response import ProjectResponse
from ..types.update_project_tier_response import UpdateProjectTierResponse
from .raw_client import AsyncRawProjectsClient, RawProjectsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProjectsClient
        """
        return self._raw_client

    def get_project(self, *, request_options: typing.Optional[RequestOptions] = None) -> ProjectResponse:
        """
        Returns full project info for the dashboard.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectResponse
            Project details

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.projects.get_project()
        """
        _response = self._raw_client.get_project(request_options=request_options)
        return _response.data

    def create_project(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateProjectResponse:
        """
        Creates a new project with an initial API key. Gated on email verification.

        Parameters
        ----------
        name : str
            1-128 chars.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateProjectResponse
            Project created. The `api_key` field is returned exactly once.

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.projects.create_project(
            name="name",
        )
        """
        _response = self._raw_client.create_project(name=name, request_options=request_options)
        return _response.data

    def update_project_tier(
        self, id: str, *, tier: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateProjectTierResponse:
        """
        Internal sync endpoint used by the dashboard after Polar.sh webhook
        processing. Gated by `BRUME_INTERNAL_TOKEN`.

        Parameters
        ----------
        id : str
            Hex-encoded project id (16 bytes → 32 hex chars).

        tier : str
            One of `"free" | "starter" | "pro" | "business"`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateProjectTierResponse
            Tier updated

        Examples
        --------
        from brume import BrumeClient

        client = BrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.projects.update_project_tier(
            id="id",
            tier="tier",
        )
        """
        _response = self._raw_client.update_project_tier(id, tier=tier, request_options=request_options)
        return _response.data


class AsyncProjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProjectsClient
        """
        return self._raw_client

    async def get_project(self, *, request_options: typing.Optional[RequestOptions] = None) -> ProjectResponse:
        """
        Returns full project info for the dashboard.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProjectResponse
            Project details

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.projects.get_project()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_project(request_options=request_options)
        return _response.data

    async def create_project(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateProjectResponse:
        """
        Creates a new project with an initial API key. Gated on email verification.

        Parameters
        ----------
        name : str
            1-128 chars.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateProjectResponse
            Project created. The `api_key` field is returned exactly once.

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.projects.create_project(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_project(name=name, request_options=request_options)
        return _response.data

    async def update_project_tier(
        self, id: str, *, tier: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateProjectTierResponse:
        """
        Internal sync endpoint used by the dashboard after Polar.sh webhook
        processing. Gated by `BRUME_INTERNAL_TOKEN`.

        Parameters
        ----------
        id : str
            Hex-encoded project id (16 bytes → 32 hex chars).

        tier : str
            One of `"free" | "starter" | "pro" | "business"`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateProjectTierResponse
            Tier updated

        Examples
        --------
        import asyncio

        from brume import AsyncBrumeClient

        client = AsyncBrumeClient(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.projects.update_project_tier(
                id="id",
                tier="tier",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_project_tier(id, tier=tier, request_options=request_options)
        return _response.data
