// Code generated by Fern. DO NOT EDIT.

package channels

import (
    context "context"
    os "os"

    brume "github.com/brumehq/brume-rest-go"
    core "github.com/brumehq/brume-rest-go/core"
    internal "github.com/brumehq/brume-rest-go/internal"
    option "github.com/brumehq/brume-rest-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.APIKey == "" {
        options.APIKey = os.Getenv("BRUME_API_KEY")
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Returns a list of all channels for the authenticated project.
func (c *Client) ListChannels(
    ctx context.Context,
    opts ...option.RequestOption,
) (*brume.ChannelListResponse, error){
    response, err := c.WithRawResponse.ListChannels(
        ctx,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Returns the current presence roster for a channel.
func (c *Client) GetPresence(
    ctx context.Context,
    // Channel name. Same rules as publish.
    channel string,
    opts ...option.RequestOption,
) (*brume.PresenceResponse, error){
    response, err := c.WithRawResponse.GetPresence(
        ctx,
        channel,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Server-side REST publish endpoint for non-WebSocket backends
// (cron jobs, webhooks, queue workers).
func (c *Client) Publish(
    ctx context.Context,
    // Channel name. Must contain at least one `:` separator (e.g., `room:123`). 1-256 chars. Allowed: alphanumeric, `:`, `-`, `_`.
    channel string,
    request *brume.PublishRequest,
    opts ...option.RequestOption,
) (*brume.PublishResponse, error){
    response, err := c.WithRawResponse.Publish(
        ctx,
        channel,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// JWT extraction priority:
// 1. `Sec-WebSocket-Protocol: brume.token.<jwt>` (recommended — keeps the
//    token out of access logs, browser history, and referer headers).
// 2. `?token=<jwt>` query parameter (legacy; emits a deprecation warning).
// 
// If auth fails, returns an HTTP error response without upgrading.
func (c *Client) Connect(
    ctx context.Context,
    request *brume.ConnectRequest,
    opts ...option.RequestOption,
) error{
    _, err := c.WithRawResponse.Connect(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return err
    }
    return nil
}

