// Code generated by Fern. DO NOT EDIT.

package public

import (
    context "context"
    http "net/http"

    brume "github.com/brumehq/brume-rest-go"
    core "github.com/brumehq/brume-rest-go/core"
    internal "github.com/brumehq/brume-rest-go/internal"
    option "github.com/brumehq/brume-rest-go/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) Health(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := baseURL + "/health"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: nil,
    }, nil
}

func (r *RawClient) Metrics(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := baseURL + "/metrics"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: nil,
    }, nil
}

func (r *RawClient) OpenapiSpec(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := baseURL + "/openapi.json"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: nil,
    }, nil
}

func (r *RawClient) Readyz(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*brume.ReadyzResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := baseURL + "/readyz"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *brume.ReadyzResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(brume.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*brume.ReadyzResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

