// Code generated by Fern. DO NOT EDIT.

package brume

import (
	json "encoding/json"
	core "github.com/brumehq/brume-rest-go/core"
)

// Invalid request body
type BadRequestError struct {
	*core.APIError
	Body any
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Payload exceeds 64KB
type ContentTooLargeError struct {
	*core.APIError
	Body *ErrorBody
}

func (c *ContentTooLargeError) UnmarshalJSON(data []byte) error {
	var body *ErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 413
	c.Body = body
	return nil
}

func (c *ContentTooLargeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ContentTooLargeError) Unwrap() error {
	return c.APIError
}

// Key lacks `read_stats` scope
type ForbiddenError struct {
	*core.APIError
	Body *ErrorBody
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body *ErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// Key not found in this project
type NotFoundError struct {
	*core.APIError
	Body *ErrorBody
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Postgres pool is closed or unreachable
type ServiceUnavailableError struct {
	*core.APIError
	Body any
}

func (s *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 503
	s.Body = body
	return nil
}

func (s *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *ServiceUnavailableError) Unwrap() error {
	return s.APIError
}

// Project hit the per-project API key cap
type TooManyRequestsError struct {
	*core.APIError
	Body any
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Missing or invalid API key
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorBody
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
