// Code generated by Fern. DO NOT EDIT.

package brume

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/brumehq/brume-rest-go/internal"
	big "math/big"
)

// `GET /readyz` success body. The 200 / 503 distinction is what load
// balancers key on; the body is for human debugging.
var (
	readyzResponseFieldStatus = big.NewInt(1 << 0)
)

type ReadyzResponse struct {
	// Always `"ready"`.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReadyzResponse) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *ReadyzResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReadyzResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyzResponse) SetStatus(status string) {
	r.Status = status
	r.require(readyzResponseFieldStatus)
}

func (r *ReadyzResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReadyzResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReadyzResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReadyzResponse) MarshalJSON() ([]byte, error) {
	type embed ReadyzResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReadyzResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
