// Code generated by Fern. DO NOT EDIT.

package brume

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/brumehq/brume-rest-go/internal"
	big "math/big"
)

var (
	createWebhookRequestFieldEvents = big.NewInt(1 << 0)
	createWebhookRequestFieldURL    = big.NewInt(1 << 1)
)

type CreateWebhookRequest struct {
	// Event names to subscribe to (e.g. `["channel.message.published"]`).
	Events []string `json:"events" url:"-"`
	// Destination URL. Validated by `webhook_validation::validate_webhook_url`.
	URL string `json:"url" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateWebhookRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhookRequest) SetEvents(events []string) {
	c.Events = events
	c.require(createWebhookRequestFieldEvents)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhookRequest) SetURL(url string) {
	c.URL = url
	c.require(createWebhookRequestFieldURL)
}

func (c *CreateWebhookRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWebhookRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateWebhookRequest(body)
	return nil
}

func (c *CreateWebhookRequest) MarshalJSON() ([]byte, error) {
	type embed CreateWebhookRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// `POST /v1/webhooks` success response. Includes the `secret` field
// which is only returned at creation time.
var (
	webhookCreatedResponseFieldEvents = big.NewInt(1 << 0)
	webhookCreatedResponseFieldID     = big.NewInt(1 << 1)
	webhookCreatedResponseFieldSecret = big.NewInt(1 << 2)
	webhookCreatedResponseFieldURL    = big.NewInt(1 << 3)
)

type WebhookCreatedResponse struct {
	Events []string `json:"events" url:"events"`
	ID     string   `json:"id" url:"id"`
	// HMAC-SHA256 secret used to sign deliveries. Only returned once.
	Secret string `json:"secret" url:"secret"`
	URL    string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookCreatedResponse) GetEvents() []string {
	if w == nil {
		return nil
	}
	return w.Events
}

func (w *WebhookCreatedResponse) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookCreatedResponse) GetSecret() string {
	if w == nil {
		return ""
	}
	return w.Secret
}

func (w *WebhookCreatedResponse) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookCreatedResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookCreatedResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatedResponse) SetEvents(events []string) {
	w.Events = events
	w.require(webhookCreatedResponseFieldEvents)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatedResponse) SetID(id string) {
	w.ID = id
	w.require(webhookCreatedResponseFieldID)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatedResponse) SetSecret(secret string) {
	w.Secret = secret
	w.require(webhookCreatedResponseFieldSecret)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatedResponse) SetURL(url string) {
	w.URL = url
	w.require(webhookCreatedResponseFieldURL)
}

func (w *WebhookCreatedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookCreatedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookCreatedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookCreatedResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookCreatedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookCreatedResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// `DELETE /v1/webhooks/:id` success response.
var (
	webhookDeleteResponseFieldStatus = big.NewInt(1 << 0)
)

type WebhookDeleteResponse struct {
	// Always `"deleted"`.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookDeleteResponse) GetStatus() string {
	if w == nil {
		return ""
	}
	return w.Status
}

func (w *WebhookDeleteResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookDeleteResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeleteResponse) SetStatus(status string) {
	w.Status = status
	w.require(webhookDeleteResponseFieldStatus)
}

func (w *WebhookDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookDeleteResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookDeleteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookDeleteResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	webhookDeliveryItemFieldAttempts       = big.NewInt(1 << 0)
	webhookDeliveryItemFieldCreatedAt      = big.NewInt(1 << 1)
	webhookDeliveryItemFieldEventType      = big.NewInt(1 << 2)
	webhookDeliveryItemFieldID             = big.NewInt(1 << 3)
	webhookDeliveryItemFieldLastAttemptAt  = big.NewInt(1 << 4)
	webhookDeliveryItemFieldResponseStatus = big.NewInt(1 << 5)
	webhookDeliveryItemFieldStatus         = big.NewInt(1 << 6)
)

type WebhookDeliveryItem struct {
	Attempts int `json:"attempts" url:"attempts"`
	// RFC-3339 timestamp of delivery creation.
	CreatedAt string `json:"created_at" url:"created_at"`
	EventType string `json:"event_type" url:"event_type"`
	ID        string `json:"id" url:"id"`
	// RFC-3339 timestamp of the most recent attempt, or `null`.
	LastAttemptAt *string `json:"last_attempt_at,omitempty" url:"last_attempt_at,omitempty"`
	// HTTP status code of the most recent attempt, or `null`.
	ResponseStatus *int `json:"response_status,omitempty" url:"response_status,omitempty"`
	// `"pending" | "delivered" | "failed"`.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookDeliveryItem) GetAttempts() int {
	if w == nil {
		return 0
	}
	return w.Attempts
}

func (w *WebhookDeliveryItem) GetCreatedAt() string {
	if w == nil {
		return ""
	}
	return w.CreatedAt
}

func (w *WebhookDeliveryItem) GetEventType() string {
	if w == nil {
		return ""
	}
	return w.EventType
}

func (w *WebhookDeliveryItem) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookDeliveryItem) GetLastAttemptAt() *string {
	if w == nil {
		return nil
	}
	return w.LastAttemptAt
}

func (w *WebhookDeliveryItem) GetResponseStatus() *int {
	if w == nil {
		return nil
	}
	return w.ResponseStatus
}

func (w *WebhookDeliveryItem) GetStatus() string {
	if w == nil {
		return ""
	}
	return w.Status
}

func (w *WebhookDeliveryItem) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookDeliveryItem) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetAttempts sets the Attempts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetAttempts(attempts int) {
	w.Attempts = attempts
	w.require(webhookDeliveryItemFieldAttempts)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetCreatedAt(createdAt string) {
	w.CreatedAt = createdAt
	w.require(webhookDeliveryItemFieldCreatedAt)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetEventType(eventType string) {
	w.EventType = eventType
	w.require(webhookDeliveryItemFieldEventType)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetID(id string) {
	w.ID = id
	w.require(webhookDeliveryItemFieldID)
}

// SetLastAttemptAt sets the LastAttemptAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetLastAttemptAt(lastAttemptAt *string) {
	w.LastAttemptAt = lastAttemptAt
	w.require(webhookDeliveryItemFieldLastAttemptAt)
}

// SetResponseStatus sets the ResponseStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetResponseStatus(responseStatus *int) {
	w.ResponseStatus = responseStatus
	w.require(webhookDeliveryItemFieldResponseStatus)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryItem) SetStatus(status string) {
	w.Status = status
	w.require(webhookDeliveryItemFieldStatus)
}

func (w *WebhookDeliveryItem) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookDeliveryItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookDeliveryItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookDeliveryItem) MarshalJSON() ([]byte, error) {
	type embed WebhookDeliveryItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookDeliveryItem) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// `GET /v1/webhooks/:id/deliveries` success response.
var (
	webhookDeliveryListResponseFieldDeliveries = big.NewInt(1 << 0)
)

type WebhookDeliveryListResponse struct {
	Deliveries []*WebhookDeliveryItem `json:"deliveries" url:"deliveries"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookDeliveryListResponse) GetDeliveries() []*WebhookDeliveryItem {
	if w == nil {
		return nil
	}
	return w.Deliveries
}

func (w *WebhookDeliveryListResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookDeliveryListResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetDeliveries sets the Deliveries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookDeliveryListResponse) SetDeliveries(deliveries []*WebhookDeliveryItem) {
	w.Deliveries = deliveries
	w.require(webhookDeliveryListResponseFieldDeliveries)
}

func (w *WebhookDeliveryListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookDeliveryListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookDeliveryListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookDeliveryListResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookDeliveryListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookDeliveryListResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// `GET /v1/webhooks` success response.
var (
	webhookListResponseFieldWebhooks = big.NewInt(1 << 0)
)

type WebhookListResponse struct {
	Webhooks []*WebhookSummary `json:"webhooks" url:"webhooks"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookListResponse) GetWebhooks() []*WebhookSummary {
	if w == nil {
		return nil
	}
	return w.Webhooks
}

func (w *WebhookListResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookListResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWebhooks sets the Webhooks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookListResponse) SetWebhooks(webhooks []*WebhookSummary) {
	w.Webhooks = webhooks
	w.require(webhookListResponseFieldWebhooks)
}

func (w *WebhookListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookListResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookListResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	webhookSummaryFieldCreatedAt = big.NewInt(1 << 0)
	webhookSummaryFieldEvents    = big.NewInt(1 << 1)
	webhookSummaryFieldID        = big.NewInt(1 << 2)
	webhookSummaryFieldURL       = big.NewInt(1 << 3)
)

type WebhookSummary struct {
	// RFC-3339 creation timestamp.
	CreatedAt string   `json:"created_at" url:"created_at"`
	Events    []string `json:"events" url:"events"`
	ID        string   `json:"id" url:"id"`
	URL       string   `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookSummary) GetCreatedAt() string {
	if w == nil {
		return ""
	}
	return w.CreatedAt
}

func (w *WebhookSummary) GetEvents() []string {
	if w == nil {
		return nil
	}
	return w.Events
}

func (w *WebhookSummary) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookSummary) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookSummary) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookSummary) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSummary) SetCreatedAt(createdAt string) {
	w.CreatedAt = createdAt
	w.require(webhookSummaryFieldCreatedAt)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSummary) SetEvents(events []string) {
	w.Events = events
	w.require(webhookSummaryFieldEvents)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSummary) SetID(id string) {
	w.ID = id
	w.require(webhookSummaryFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSummary) SetURL(url string) {
	w.URL = url
	w.require(webhookSummaryFieldURL)
}

func (w *WebhookSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookSummary) MarshalJSON() ([]byte, error) {
	type embed WebhookSummary
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookSummary) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// `POST /v1/webhooks/:id/test` success response.
var (
	webhookTestResponseFieldStatus = big.NewInt(1 << 0)
)

type WebhookTestResponse struct {
	// Always `"queued"`. The actual delivery runs asynchronously.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookTestResponse) GetStatus() string {
	if w == nil {
		return ""
	}
	return w.Status
}

func (w *WebhookTestResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookTestResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookTestResponse) SetStatus(status string) {
	w.Status = status
	w.require(webhookTestResponseFieldStatus)
}

func (w *WebhookTestResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookTestResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookTestResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookTestResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookTestResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookTestResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
