/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ApiKeyListResponse.Builder.class
)
public final class ApiKeyListResponse {
  private final List<ApiKeyListItem> apiKeys;

  private final Map<String, Object> additionalProperties;

  private ApiKeyListResponse(List<ApiKeyListItem> apiKeys,
      Map<String, Object> additionalProperties) {
    this.apiKeys = apiKeys;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("api_keys")
  public List<ApiKeyListItem> getApiKeys() {
    return apiKeys;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ApiKeyListResponse && equalTo((ApiKeyListResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ApiKeyListResponse other) {
    return apiKeys.equals(other.apiKeys);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKeys);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<ApiKeyListItem> apiKeys = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ApiKeyListResponse other) {
      apiKeys(other.getApiKeys());
      return this;
    }

    @JsonSetter(
        value = "api_keys",
        nulls = Nulls.SKIP
    )
    public Builder apiKeys(List<ApiKeyListItem> apiKeys) {
      this.apiKeys.clear();
      if (apiKeys != null) {
        this.apiKeys.addAll(apiKeys);
      }
      return this;
    }

    public Builder addApiKeys(ApiKeyListItem apiKeys) {
      this.apiKeys.add(apiKeys);
      return this;
    }

    public Builder addAllApiKeys(List<ApiKeyListItem> apiKeys) {
      if (apiKeys != null) {
        this.apiKeys.addAll(apiKeys);
      }
      return this;
    }

    public ApiKeyListResponse build() {
      return new ApiKeyListResponse(apiKeys, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
