/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ChannelListResponse.Builder.class
)
public final class ChannelListResponse {
  private final List<ChannelSummary> channels;

  private final Map<String, Object> additionalProperties;

  private ChannelListResponse(List<ChannelSummary> channels,
      Map<String, Object> additionalProperties) {
    this.channels = channels;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("channels")
  public List<ChannelSummary> getChannels() {
    return channels;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ChannelListResponse && equalTo((ChannelListResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ChannelListResponse other) {
    return channels.equals(other.channels);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.channels);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<ChannelSummary> channels = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ChannelListResponse other) {
      channels(other.getChannels());
      return this;
    }

    @JsonSetter(
        value = "channels",
        nulls = Nulls.SKIP
    )
    public Builder channels(List<ChannelSummary> channels) {
      this.channels.clear();
      if (channels != null) {
        this.channels.addAll(channels);
      }
      return this;
    }

    public Builder addChannels(ChannelSummary channels) {
      this.channels.add(channels);
      return this;
    }

    public Builder addAllChannels(List<ChannelSummary> channels) {
      if (channels != null) {
        this.channels.addAll(channels);
      }
      return this;
    }

    public ChannelListResponse build() {
      return new ChannelListResponse(channels, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
