/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateApiKeyResponse.Builder.class
)
public final class CreateApiKeyResponse {
  private final String environment;

  private final String id;

  private final String key;

  private final String label;

  private final String prefix;

  private final List<ApiKeyScope> scopes;

  private final Map<String, Object> additionalProperties;

  private CreateApiKeyResponse(String environment, String id, String key, String label,
      String prefix, List<ApiKeyScope> scopes, Map<String, Object> additionalProperties) {
    this.environment = environment;
    this.id = id;
    this.key = key;
    this.label = label;
    this.prefix = prefix;
    this.scopes = scopes;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("environment")
  public String getEnvironment() {
    return environment;
  }

  /**
   * @return Hex-encoded key id.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The raw API key. Only returned by the create endpoint.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  @JsonProperty("label")
  public String getLabel() {
    return label;
  }

  /**
   * @return 28-char prefix used for O(1) lookup. Safe to display.
   */
  @JsonProperty("prefix")
  public String getPrefix() {
    return prefix;
  }

  /**
   * @return Granted scopes (E6). Serializes as the snake_case string form
   * (<code>&quot;publish&quot;</code>, <code>&quot;read_stats&quot;</code>, <code>&quot;manage_keys&quot;</code>, <code>&quot;manage_project&quot;</code>).
   */
  @JsonProperty("scopes")
  public List<ApiKeyScope> getScopes() {
    return scopes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateApiKeyResponse && equalTo((CreateApiKeyResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateApiKeyResponse other) {
    return environment.equals(other.environment) && id.equals(other.id) && key.equals(other.key) && label.equals(other.label) && prefix.equals(other.prefix) && scopes.equals(other.scopes);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.environment, this.id, this.key, this.label, this.prefix, this.scopes);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EnvironmentStage builder() {
    return new Builder();
  }

  public interface EnvironmentStage {
    IdStage environment(@NotNull String environment);

    Builder from(CreateApiKeyResponse other);
  }

  public interface IdStage {
    /**
     * <p>Hex-encoded key id.</p>
     */
    KeyStage id(@NotNull String id);
  }

  public interface KeyStage {
    /**
     * <p>The raw API key. Only returned by the create endpoint.</p>
     */
    LabelStage key(@NotNull String key);
  }

  public interface LabelStage {
    PrefixStage label(@NotNull String label);
  }

  public interface PrefixStage {
    /**
     * <p>28-char prefix used for O(1) lookup. Safe to display.</p>
     */
    _FinalStage prefix(@NotNull String prefix);
  }

  public interface _FinalStage {
    CreateApiKeyResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Granted scopes (E6). Serializes as the snake_case string form
     * (<code>&quot;publish&quot;</code>, <code>&quot;read_stats&quot;</code>, <code>&quot;manage_keys&quot;</code>, <code>&quot;manage_project&quot;</code>).</p>
     */
    _FinalStage scopes(List<ApiKeyScope> scopes);

    _FinalStage addScopes(ApiKeyScope scopes);

    _FinalStage addAllScopes(List<ApiKeyScope> scopes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EnvironmentStage, IdStage, KeyStage, LabelStage, PrefixStage, _FinalStage {
    private String environment;

    private String id;

    private String key;

    private String label;

    private String prefix;

    private List<ApiKeyScope> scopes = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateApiKeyResponse other) {
      environment(other.getEnvironment());
      id(other.getId());
      key(other.getKey());
      label(other.getLabel());
      prefix(other.getPrefix());
      scopes(other.getScopes());
      return this;
    }

    @java.lang.Override
    @JsonSetter("environment")
    public IdStage environment(@NotNull String environment) {
      this.environment = Objects.requireNonNull(environment, "environment must not be null");
      return this;
    }

    /**
     * <p>Hex-encoded key id.</p>
     * <p>Hex-encoded key id.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public KeyStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The raw API key. Only returned by the create endpoint.</p>
     * <p>The raw API key. Only returned by the create endpoint.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public LabelStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("label")
    public PrefixStage label(@NotNull String label) {
      this.label = Objects.requireNonNull(label, "label must not be null");
      return this;
    }

    /**
     * <p>28-char prefix used for O(1) lookup. Safe to display.</p>
     * <p>28-char prefix used for O(1) lookup. Safe to display.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prefix")
    public _FinalStage prefix(@NotNull String prefix) {
      this.prefix = Objects.requireNonNull(prefix, "prefix must not be null");
      return this;
    }

    /**
     * <p>Granted scopes (E6). Serializes as the snake_case string form
     * (<code>&quot;publish&quot;</code>, <code>&quot;read_stats&quot;</code>, <code>&quot;manage_keys&quot;</code>, <code>&quot;manage_project&quot;</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllScopes(List<ApiKeyScope> scopes) {
      if (scopes != null) {
        this.scopes.addAll(scopes);
      }
      return this;
    }

    /**
     * <p>Granted scopes (E6). Serializes as the snake_case string form
     * (<code>&quot;publish&quot;</code>, <code>&quot;read_stats&quot;</code>, <code>&quot;manage_keys&quot;</code>, <code>&quot;manage_project&quot;</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addScopes(ApiKeyScope scopes) {
      this.scopes.add(scopes);
      return this;
    }

    /**
     * <p>Granted scopes (E6). Serializes as the snake_case string form
     * (<code>&quot;publish&quot;</code>, <code>&quot;read_stats&quot;</code>, <code>&quot;manage_keys&quot;</code>, <code>&quot;manage_project&quot;</code>).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scopes",
        nulls = Nulls.SKIP
    )
    public _FinalStage scopes(List<ApiKeyScope> scopes) {
      this.scopes.clear();
      if (scopes != null) {
        this.scopes.addAll(scopes);
      }
      return this;
    }

    @java.lang.Override
    public CreateApiKeyResponse build() {
      return new CreateApiKeyResponse(environment, id, key, label, prefix, scopes, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
