/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateWebhookRequest.Builder.class
)
public final class CreateWebhookRequest {
  private final List<String> events;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private CreateWebhookRequest(List<String> events, String url,
      Map<String, Object> additionalProperties) {
    this.events = events;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Event names to subscribe to (e.g. <code>[&quot;channel.message.published&quot;]</code>).
   */
  @JsonProperty("events")
  public List<String> getEvents() {
    return events;
  }

  /**
   * @return Destination URL. Validated by <code>webhook_validation::validate_webhook_url</code>.
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateWebhookRequest && equalTo((CreateWebhookRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateWebhookRequest other) {
    return events.equals(other.events) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.events, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>Destination URL. Validated by <code>webhook_validation::validate_webhook_url</code>.</p>
     */
    _FinalStage url(@NotNull String url);

    Builder from(CreateWebhookRequest other);
  }

  public interface _FinalStage {
    CreateWebhookRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Event names to subscribe to (e.g. <code>[&quot;channel.message.published&quot;]</code>).</p>
     */
    _FinalStage events(List<String> events);

    _FinalStage addEvents(String events);

    _FinalStage addAllEvents(List<String> events);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private List<String> events = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateWebhookRequest other) {
      events(other.getEvents());
      url(other.getUrl());
      return this;
    }

    /**
     * <p>Destination URL. Validated by <code>webhook_validation::validate_webhook_url</code>.</p>
     * <p>Destination URL. Validated by <code>webhook_validation::validate_webhook_url</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>Event names to subscribe to (e.g. <code>[&quot;channel.message.published&quot;]</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvents(List<String> events) {
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    /**
     * <p>Event names to subscribe to (e.g. <code>[&quot;channel.message.published&quot;]</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvents(String events) {
      this.events.add(events);
      return this;
    }

    /**
     * <p>Event names to subscribe to (e.g. <code>[&quot;channel.message.published&quot;]</code>).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public _FinalStage events(List<String> events) {
      this.events.clear();
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public CreateWebhookRequest build() {
      return new CreateWebhookRequest(events, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
