/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = NotReadyResponse.Builder.class
)
public final class NotReadyResponse {
  private final String reason;

  private final String status;

  private final Map<String, Object> additionalProperties;

  private NotReadyResponse(String reason, String status, Map<String, Object> additionalProperties) {
    this.reason = reason;
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return One of: <code>&quot;db pool closed&quot;</code>, <code>&quot;db query failed&quot;</code>, <code>&quot;db query timeout&quot;</code>.
   */
  @JsonProperty("reason")
  public String getReason() {
    return reason;
  }

  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof NotReadyResponse && equalTo((NotReadyResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(NotReadyResponse other) {
    return reason.equals(other.reason) && status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.reason, this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ReasonStage builder() {
    return new Builder();
  }

  public interface ReasonStage {
    /**
     * <p>One of: <code>&quot;db pool closed&quot;</code>, <code>&quot;db query failed&quot;</code>, <code>&quot;db query timeout&quot;</code>.</p>
     */
    StatusStage reason(@NotNull String reason);

    Builder from(NotReadyResponse other);
  }

  public interface StatusStage {
    _FinalStage status(@NotNull String status);
  }

  public interface _FinalStage {
    NotReadyResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ReasonStage, StatusStage, _FinalStage {
    private String reason;

    private String status;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(NotReadyResponse other) {
      reason(other.getReason());
      status(other.getStatus());
      return this;
    }

    /**
     * <p>One of: <code>&quot;db pool closed&quot;</code>, <code>&quot;db query failed&quot;</code>, <code>&quot;db query timeout&quot;</code>.</p>
     * <p>One of: <code>&quot;db pool closed&quot;</code>, <code>&quot;db query failed&quot;</code>, <code>&quot;db query timeout&quot;</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("reason")
    public StatusStage reason(@NotNull String reason) {
      this.reason = Objects.requireNonNull(reason, "reason must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public NotReadyResponse build() {
      return new NotReadyResponse(reason, status, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
