/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ProjectResponse.Builder.class
)
public final class ProjectResponse {
  private final String createdAt;

  private final String id;

  private final long maxConnections;

  private final String name;

  private final String tier;

  private final Map<String, Object> additionalProperties;

  private ProjectResponse(String createdAt, String id, long maxConnections, String name,
      String tier, Map<String, Object> additionalProperties) {
    this.createdAt = createdAt;
    this.id = id;
    this.maxConnections = maxConnections;
    this.name = name;
    this.tier = tier;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return RFC-3339 timestamp of project creation.
   */
  @JsonProperty("created_at")
  public String getCreatedAt() {
    return createdAt;
  }

  /**
   * @return Hex-encoded 16-byte project id.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("max_connections")
  public long getMaxConnections() {
    return maxConnections;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("tier")
  public String getTier() {
    return tier;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ProjectResponse && equalTo((ProjectResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ProjectResponse other) {
    return createdAt.equals(other.createdAt) && id.equals(other.id) && maxConnections == other.maxConnections && name.equals(other.name) && tier.equals(other.tier);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.createdAt, this.id, this.maxConnections, this.name, this.tier);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CreatedAtStage builder() {
    return new Builder();
  }

  public interface CreatedAtStage {
    /**
     * <p>RFC-3339 timestamp of project creation.</p>
     */
    IdStage createdAt(@NotNull String createdAt);

    Builder from(ProjectResponse other);
  }

  public interface IdStage {
    /**
     * <p>Hex-encoded 16-byte project id.</p>
     */
    MaxConnectionsStage id(@NotNull String id);
  }

  public interface MaxConnectionsStage {
    NameStage maxConnections(long maxConnections);
  }

  public interface NameStage {
    TierStage name(@NotNull String name);
  }

  public interface TierStage {
    _FinalStage tier(@NotNull String tier);
  }

  public interface _FinalStage {
    ProjectResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CreatedAtStage, IdStage, MaxConnectionsStage, NameStage, TierStage, _FinalStage {
    private String createdAt;

    private String id;

    private long maxConnections;

    private String name;

    private String tier;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ProjectResponse other) {
      createdAt(other.getCreatedAt());
      id(other.getId());
      maxConnections(other.getMaxConnections());
      name(other.getName());
      tier(other.getTier());
      return this;
    }

    /**
     * <p>RFC-3339 timestamp of project creation.</p>
     * <p>RFC-3339 timestamp of project creation.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("created_at")
    public IdStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    /**
     * <p>Hex-encoded 16-byte project id.</p>
     * <p>Hex-encoded 16-byte project id.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public MaxConnectionsStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("max_connections")
    public NameStage maxConnections(long maxConnections) {
      this.maxConnections = maxConnections;
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public TierStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("tier")
    public _FinalStage tier(@NotNull String tier) {
      this.tier = Objects.requireNonNull(tier, "tier must not be null");
      return this;
    }

    @java.lang.Override
    public ProjectResponse build() {
      return new ProjectResponse(createdAt, id, maxConnections, name, tier, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
