/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PublishResponse.Builder.class
)
public final class PublishResponse {
  private final String channel;

  private final String event;

  private final int recipients;

  private final String status;

  private final Map<String, Object> additionalProperties;

  private PublishResponse(String channel, String event, int recipients, String status,
      Map<String, Object> additionalProperties) {
    this.channel = channel;
    this.event = event;
    this.recipients = recipients;
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("channel")
  public String getChannel() {
    return channel;
  }

  @JsonProperty("event")
  public String getEvent() {
    return event;
  }

  /**
   * @return Number of subscribers the message was fanned out to.
   */
  @JsonProperty("recipients")
  public int getRecipients() {
    return recipients;
  }

  /**
   * @return Always <code>&quot;published&quot;</code>. Reserved for future state changes.
   */
  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PublishResponse && equalTo((PublishResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PublishResponse other) {
    return channel.equals(other.channel) && event.equals(other.event) && recipients == other.recipients && status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.channel, this.event, this.recipients, this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ChannelStage builder() {
    return new Builder();
  }

  public interface ChannelStage {
    EventStage channel(@NotNull String channel);

    Builder from(PublishResponse other);
  }

  public interface EventStage {
    RecipientsStage event(@NotNull String event);
  }

  public interface RecipientsStage {
    /**
     * <p>Number of subscribers the message was fanned out to.</p>
     */
    StatusStage recipients(int recipients);
  }

  public interface StatusStage {
    /**
     * <p>Always <code>&quot;published&quot;</code>. Reserved for future state changes.</p>
     */
    _FinalStage status(@NotNull String status);
  }

  public interface _FinalStage {
    PublishResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ChannelStage, EventStage, RecipientsStage, StatusStage, _FinalStage {
    private String channel;

    private String event;

    private int recipients;

    private String status;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PublishResponse other) {
      channel(other.getChannel());
      event(other.getEvent());
      recipients(other.getRecipients());
      status(other.getStatus());
      return this;
    }

    @java.lang.Override
    @JsonSetter("channel")
    public EventStage channel(@NotNull String channel) {
      this.channel = Objects.requireNonNull(channel, "channel must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("event")
    public RecipientsStage event(@NotNull String event) {
      this.event = Objects.requireNonNull(event, "event must not be null");
      return this;
    }

    /**
     * <p>Number of subscribers the message was fanned out to.</p>
     * <p>Number of subscribers the message was fanned out to.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("recipients")
    public StatusStage recipients(int recipients) {
      this.recipients = recipients;
      return this;
    }

    /**
     * <p>Always <code>&quot;published&quot;</code>. Reserved for future state changes.</p>
     * <p>Always <code>&quot;published&quot;</code>. Reserved for future state changes.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public PublishResponse build() {
      return new PublishResponse(channel, event, recipients, status, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
