/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RevokeApiKeyResponse.Builder.class
)
public final class RevokeApiKeyResponse {
  private final String status;

  private final Map<String, Object> additionalProperties;

  private RevokeApiKeyResponse(String status, Map<String, Object> additionalProperties) {
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Always <code>&quot;revoked&quot;</code>.
   */
  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RevokeApiKeyResponse && equalTo((RevokeApiKeyResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RevokeApiKeyResponse other) {
    return status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    /**
     * <p>Always <code>&quot;revoked&quot;</code>.</p>
     */
    _FinalStage status(@NotNull String status);

    Builder from(RevokeApiKeyResponse other);
  }

  public interface _FinalStage {
    RevokeApiKeyResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, _FinalStage {
    private String status;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RevokeApiKeyResponse other) {
      status(other.getStatus());
      return this;
    }

    /**
     * <p>Always <code>&quot;revoked&quot;</code>.</p>
     * <p>Always <code>&quot;revoked&quot;</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public RevokeApiKeyResponse build() {
      return new RevokeApiKeyResponse(status, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
