/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateProjectTierResponse.Builder.class
)
public final class UpdateProjectTierResponse {
  private final String id;

  private final long maxConnections;

  private final String tier;

  private final Map<String, Object> additionalProperties;

  private UpdateProjectTierResponse(String id, long maxConnections, String tier,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.maxConnections = maxConnections;
    this.tier = tier;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Echo of the path param (hex-encoded project id).
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("max_connections")
  public long getMaxConnections() {
    return maxConnections;
  }

  @JsonProperty("tier")
  public String getTier() {
    return tier;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateProjectTierResponse && equalTo((UpdateProjectTierResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateProjectTierResponse other) {
    return id.equals(other.id) && maxConnections == other.maxConnections && tier.equals(other.tier);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.maxConnections, this.tier);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>Echo of the path param (hex-encoded project id).</p>
     */
    MaxConnectionsStage id(@NotNull String id);

    Builder from(UpdateProjectTierResponse other);
  }

  public interface MaxConnectionsStage {
    TierStage maxConnections(long maxConnections);
  }

  public interface TierStage {
    _FinalStage tier(@NotNull String tier);
  }

  public interface _FinalStage {
    UpdateProjectTierResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, MaxConnectionsStage, TierStage, _FinalStage {
    private String id;

    private long maxConnections;

    private String tier;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateProjectTierResponse other) {
      id(other.getId());
      maxConnections(other.getMaxConnections());
      tier(other.getTier());
      return this;
    }

    /**
     * <p>Echo of the path param (hex-encoded project id).</p>
     * <p>Echo of the path param (hex-encoded project id).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public MaxConnectionsStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("max_connections")
    public TierStage maxConnections(long maxConnections) {
      this.maxConnections = maxConnections;
      return this;
    }

    @java.lang.Override
    @JsonSetter("tier")
    public _FinalStage tier(@NotNull String tier) {
      this.tier = Objects.requireNonNull(tier, "tier must not be null");
      return this;
    }

    @java.lang.Override
    public UpdateProjectTierResponse build() {
      return new UpdateProjectTierResponse(id, maxConnections, tier, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
