/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookSummary.Builder.class
)
public final class WebhookSummary {
  private final String createdAt;

  private final List<String> events;

  private final String id;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private WebhookSummary(String createdAt, List<String> events, String id, String url,
      Map<String, Object> additionalProperties) {
    this.createdAt = createdAt;
    this.events = events;
    this.id = id;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return RFC-3339 creation timestamp.
   */
  @JsonProperty("created_at")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("events")
  public List<String> getEvents() {
    return events;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookSummary && equalTo((WebhookSummary) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookSummary other) {
    return createdAt.equals(other.createdAt) && events.equals(other.events) && id.equals(other.id) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.createdAt, this.events, this.id, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CreatedAtStage builder() {
    return new Builder();
  }

  public interface CreatedAtStage {
    /**
     * <p>RFC-3339 creation timestamp.</p>
     */
    IdStage createdAt(@NotNull String createdAt);

    Builder from(WebhookSummary other);
  }

  public interface IdStage {
    UrlStage id(@NotNull String id);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    WebhookSummary build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage events(List<String> events);

    _FinalStage addEvents(String events);

    _FinalStage addAllEvents(List<String> events);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CreatedAtStage, IdStage, UrlStage, _FinalStage {
    private String createdAt;

    private String id;

    private String url;

    private List<String> events = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhookSummary other) {
      createdAt(other.getCreatedAt());
      events(other.getEvents());
      id(other.getId());
      url(other.getUrl());
      return this;
    }

    /**
     * <p>RFC-3339 creation timestamp.</p>
     * <p>RFC-3339 creation timestamp.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("created_at")
    public IdStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public UrlStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllEvents(List<String> events) {
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addEvents(String events) {
      this.events.add(events);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public _FinalStage events(List<String> events) {
      this.events.clear();
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public WebhookSummary build() {
      return new WebhookSummary(createdAt, events, id, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
