/**
 * This file was auto-generated by Fern from our API Definition.
 */

package dev.brume.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import dev.brume.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookDeliveryListResponse.Builder.class
)
public final class WebhookDeliveryListResponse {
  private final List<WebhookDeliveryItem> deliveries;

  private final Map<String, Object> additionalProperties;

  private WebhookDeliveryListResponse(List<WebhookDeliveryItem> deliveries,
      Map<String, Object> additionalProperties) {
    this.deliveries = deliveries;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("deliveries")
  public List<WebhookDeliveryItem> getDeliveries() {
    return deliveries;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookDeliveryListResponse && equalTo((WebhookDeliveryListResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookDeliveryListResponse other) {
    return deliveries.equals(other.deliveries);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.deliveries);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<WebhookDeliveryItem> deliveries = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebhookDeliveryListResponse other) {
      deliveries(other.getDeliveries());
      return this;
    }

    @JsonSetter(
        value = "deliveries",
        nulls = Nulls.SKIP
    )
    public Builder deliveries(List<WebhookDeliveryItem> deliveries) {
      this.deliveries.clear();
      if (deliveries != null) {
        this.deliveries.addAll(deliveries);
      }
      return this;
    }

    public Builder addDeliveries(WebhookDeliveryItem deliveries) {
      this.deliveries.add(deliveries);
      return this;
    }

    public Builder addAllDeliveries(List<WebhookDeliveryItem> deliveries) {
      if (deliveries != null) {
        this.deliveries.addAll(deliveries);
      }
      return this;
    }

    public WebhookDeliveryListResponse build() {
      return new WebhookDeliveryListResponse(deliveries, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
